name: Simple APK/AAB Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Node.js (with fallback)
      run: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node --version
        npm --version
        
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pandas plotly folium streamlit-folium trafilatura requests
      
    - name: Install Node dependencies
      run: |
        npm cache clean --force
        npm install
      
    - name: Build web application
      run: python build.py
      
    - name: Install Capacitor CLI globally
      run: npm install -g @capacitor/cli
      
    - name: Add Android platform
      run: npx cap add android || echo "Android platform already exists"
      
    - name: Sync Capacitor with Android
      run: npx cap sync android
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Clean Android project
      run: |
        cd android
        ./gradlew clean --stacktrace
        
    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info
        
    - name: Build release APK
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace --info
        
    - name: Build release AAB
      run: |
        cd android
        ./gradlew bundleRelease --stacktrace --info
        
    - name: List build outputs
      run: |
        find android/app/build/outputs -name "*.apk" -o -name "*.aab" || echo "No files found"
        
    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: hunting-portal-debug-apk
        path: android/app/build/outputs/apk/debug/
        
    - name: Upload release APK
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: hunting-portal-release-apk
        path: android/app/build/outputs/apk/release/
        
    - name: Upload release AAB
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: hunting-portal-release-aab
        path: android/app/build/outputs/bundle/release/
